arcane_words = """Ph'nglui mglw'nafh Cthulhu R'lyeh wgah'nagl fhtagn. Shogg mnahn' kadishtuagl throd, Cthulhuagl Dagon goka vulgtlagln ilyaa naflshogg hai Hastur ftaghu, uaaah Yoggoth nog uln hrii k'yarnak syha'h chtenff. Ngluior n'ghft ehye uln llll ph'Yoggoth nilgh'ri li'heeoth orr'enyth ph's'uhn Cthulhu Nyarlathotep gnaiih hlirgh hai na'bthnk nglloig R'lyeh, nilgh'ri vulgtlaglnnyth 'fhalma ron li'hee wgah'n vulgtlagln Cthulhu uh'e geb 'ai f'lloig uaaah athg. Geb h'athg ph's'uhn r'luh geb r'luhor throd Shub-Niggurath hlirgh cooboshu f''bthnk, nguln goka wgah'n s'uhn nglloig ah Hastur Chaugnar Faugn hai, tharanak n'gha kn'a R'lyehyar wgah'n n'gha gnaiihoth Tsathoggua ph'geb. 

Bug mg y-fhtagn ngchtenff nilgh'ri shtunggli n'gha s'uhn sgn'wahl shogg, h'ya 'fhalma Hastur 'bthnk 'ai Dagon fm'latgh yanyth nog, li'hee wgah'nagl nnnya ck'yarnak ngsgn'wahl nggeb wgah'n. H'zhro bug ph'k'yarnak ch' ooboshu 'fhalma, nglui throd Hastur Tsathoggua, cgeb bug n'gha hupadgh. Zhro sgn'wahl hafh'drnyar nnnathg lloignyth hafh'drn nay'hah ooboshu ee n'ghft syha'h y-grah'n k'yarnak fhtagn orr'e lloig, ee hafh'drnog lloigor vulgtlagln nglui ah cgoka wgah'n Nyarlathotep uln fhtagn Tsathogguaog gnaiih. Vulgtm phlegeth wgah'n nan'gha Yoggoth ch'nyth kadishtu ep ee, sll'ha f'phlegeth ph'hafh'drn throd fm'latgh ch' R'lyeh athg Tsathoggua, shagg ee hai throd shuggor shtunggli ch'. 

Stell'bsna ng'ai naflhlirgh ph'Cthulhu nnn'ai nog Cthulhu, sgn'wahl grah'n stell'bsna nafluaaah ilyaa, orr'e shugg cNyarlathotep uln. Mnahn' Shub-Niggurath fhtagn h'Shub-Niggurath y-grah'n llllyar mg nafl'bthnk, grah'n Yoggoth shaggor ph'uh'e ron shogg n'ghftoth, mg ooboshu nog gebyar f'kn'a shugg 'ai. Ooboshu throd bug Yoggoth nnny'hah kadishtu phlegeth goka bug, 'fhalma Chaugnar Faugn k'yarnak ch' y'hah kadishtu nglui 'fhalma, shtunggli y-Hastur kadishtuoth 'bthnk hai 'bthnk kn'a, ebunma hupadgh uaaah shugg hrii throd Mnahn' orr'e gof'nn naChaugnar Faugn Tsathoggua orr'e ngtharanak uaaah sll'ha ya lllloth R'lyeh, Tsathogguaagl lw'nafh wgah'n hupadghyar lw'nafh eeor cYoggoth lloigog y-r'luh ulnog. 

Stell'bsna ph'shtunggli Chaugnar Faugn goka Shub-Niggurath naflooboshu zhro ya y'hah fm'latgh nnnR'lyeh Chaugnar Faugn nghupadgh nnnwgah'n chtenff, kadishtu f'Dagon h'bug nnntharanak h'li'hee ooboshu nnnllll ph'lw'nafh Yoggoth hrii shtunggli kadishtu. Ph'hupadgh f'y'hah kn'a goka chtenff Nyarlathotep shtunggli shugg Cthulhu chtenff, gnaiih Nyarlathotep nog naee R'lyeh geb kn'a ftaghu orr'e, vulgtlagln f'nog r'luh hafh'drnog ch' vulgtm hai. Ftaghu s'uhn haior geb Dagon 'ai hupadgh f'sgn'wahl y-bug, ilyaaog nog athg y-gnaiih y'hah Hastur nog, ph'gotha grah'n 'fhalma li'hee cee chtenff sgn'wahl. Shagg y-nglui nan'ghft kn'a grah'n ee ya hlirgh, vulgtlagln stell'bsna shugg nnnehye ngkadishtu Nyarlathotep shoggnyth, n'ghft uln ngehye chtenff h'phlegeth ilyaanyth. 

Cshugg uln nilgh'ri Chaugnar Faugn orr'e r'luh ya f'ch' r'luh wgah'n tharanak y'hah nilgh'ri, 'fhalma Hastur naflfhtagn grah'n n'gha syha'h phlegeth orr'e nafln'gha Shub-Niggurath kadishtu r'luh ilyaa. Ee sgn'wahl n'ghftog throdyar uaaah zhroor ngy'hah ch' orr'e shagg naflshugg mg tharanak, chtenff n'gha chtenff n'ghft y-k'yarnak fm'latgh li'hee Azathoth 'fhalmanyth mnahn' tharanak throdnyth, nog ftaghu hupadgh shugg cchtenff lw'nafh shoggog hupadgh chtenff n'ghftyar. Tharanak phlegethagl vulgtm cuaaah f'Yoggoth phlegeth ngsll'ha 'bthnk stell'bsna vulgtm, naflee naChaugnar Faugn lloig ph'grah'n Azathothor gotha Hastur y-ehye, ebunma athg nafhtagn hrii ph'phlegeth 'ai ron nnnshugg. 

Ebunma hafh'drn kadishtu stell'bsna kadishtu Hastur Yoggoth, k'yarnak sll'ha phlegeth k'yarnak shugg ebunma k'yarnak, ehye sll'ha hrii Hastur n'ghft. Dagonnyth vulgtlaglnoth hupadgh nw nglui Shub-Niggurath n'ghft, k'yarnak fm'latgh kadishtu kn'a ron.""".split(' ')


weapon_words = 'sharp quick unpredictable shiny legendary'.split(' ')